# This is a generated file. Not intended for manual editing.
services:
  auction-svc:
    build:
      context: "/Users/raghavakv/Downloads/DriveBid"
      dockerfile: "backend/src/AuctionService/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57403"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "raghavareddykv/auction-svc:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57403"
    volumes:
    - "/Users/raghavakv/Downloads/DriveBid/backend/src/AuctionService:/app:rw"
    - "/Users/raghavakv/Downloads/DriveBid:/src:rw"
    - "/Users/raghavakv/.nuget/packages:/root/.nuget/packages"
    - "/Users/raghavakv/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/raghavakv/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/raghavakv/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_02_12_51_05:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  identity-svc:
    build:
      context: "/Users/raghavakv/Downloads/DriveBid"
      dockerfile: "backend/src/IdentityService/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57404"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/IdentityService.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "raghavareddykv/identity-svc:dev"
    ports:
    - "127.0.0.1:57004:57000"
    - "127.0.0.1:57204:57200"
    - "127.0.0.1:57404:57404"
    volumes:
    - "/Users/raghavakv/Downloads/DriveBid/backend/src/IdentityService:/app:rw"
    - "/Users/raghavakv/Downloads/DriveBid:/src:rw"
    - "/Users/raghavakv/.nuget/packages:/root/.nuget/packages"
    - "/Users/raghavakv/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/raghavakv/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/raghavakv/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_02_12_51_05:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  search-svc:
    build:
      context: "/Users/raghavakv/Downloads/DriveBid"
      dockerfile: "backend/src/SearchService/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57405"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "raghavareddykv/search-svc:dev"
    ports:
    - "127.0.0.1:57005:57000"
    - "127.0.0.1:57205:57200"
    - "127.0.0.1:57405:57405"
    volumes:
    - "/Users/raghavakv/Downloads/DriveBid/backend/src/SearchService:/app:rw"
    - "/Users/raghavakv/Downloads/DriveBid:/src:rw"
    - "/Users/raghavakv/.nuget/packages:/root/.nuget/packages"
    - "/Users/raghavakv/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/raghavakv/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/raghavakv/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_02_12_51_05:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
