apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  labels:
    name: ingress-svc
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.drivebid.local
        - api.drivebid.local
        - id.drivebid.local
      secretName: drivebid-app-tls
  rules:
    - host: app.drivebid.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: webapp-clusterip
                port:
                  number: 3000
    - host: api.drivebid.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: gateway-clusterip
                port:
                  number: 80
    - host: id.drivebid.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: identity-clusterip
                port:
                  number: 80